name: "CI"

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  terraform-vm:
    defaults:
      run:
        working-directory: "terraform/vm"

    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out plan

      - name: Terraform Apply
        run: terraform apply -auto-approve "plan"

  terraform-peering:
    defaults:
      run:
        working-directory: "terraform/peering"

    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out plan

      - name: Terraform Apply
        run: terraform apply -auto-approve "plan"
