name: "Destroy"

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  terraform-destroy:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    strategy:
      matrix:
        cwd:
        - 'terraform/db'
        - 'terraform/vm'
        - 'terraform/vnet-peering'

    defaults:
      run:
        working-directory: ${{ matrix.cwd }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Destroy
        run: terraform apply -auto-approve -destroy
